name: setup and check
on: push
jobs:
  setup-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          cache: 'npm'
      - run: make install
      - run: make test
      - run: make lint
#      - uses: paambaati/codeclimate-action@v3.0.0
#        env:
#          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_ID }}
#        with:
#          coverageCommand: make coverage
#          debug: true
